
  0% 0/1 [00:00<?, ?it/s]
Data path:  /Tmp/slurm.1934960.0/home/mila/a/aditya.jain/scratch/GBIF_Data/moths_uk
{
   "note": "This config file is for training on the complete macromoths dataset",
   "model": {
      "species_num_classes": 992,
      "genus_num_classes": 495,
      "family_num_classes": 18,
      "type": "resnet50"
   },
   "dataset": {
      "root_dir": "/home/mila/a/aditya.jain/scratch/GBIF_Data/moths_uk/",
      "train_set": "/home/mila/a/aditya.jain/mothAI/classification_moths/data/01-uk-train-split.csv",
      "val_set": "/home/mila/a/aditya.jain/mothAI/classification_moths/data/01-uk-val-split.csv",
      "test_set": "/home/mila/a/aditya.jain/mothAI/classification_moths/data/01-uk-test-split.csv",
      "label_info": "/home/mila/a/aditya.jain/mothAI/classification_moths/data/uk_numeric_labels.json",
      "taxon_hierarchy": "/home/mila/a/aditya.jain/mothAI/classification_moths/data/uk_taxon_hierarchy.json"
   },
   "training": {
      "batch_size": 64,
      "image_resize": 300,
      "epochs": 1,
      "early_stopping": 4,
      "start_val_loss": 100000000,
      "loss": {
         "name": "crossentropy"
      },
      "optimizer": {
         "name": "sgd",
         "learning_rate": 0.001,
         "momentum": 0.9
      },
      "model_save_path": "/home/mila/a/aditya.jain/logs/",
      "model_name": "uk-moth-model",
      "version": "v01"
   }
}
  0% 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_uk.py", line 156, in <module>
    for image_batch, label_batch in train_dataloader:
  File "/home/mila/a/aditya.jain/.conda/envs/milamoth/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/mila/a/aditya.jain/.conda/envs/milamoth/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/mila/a/aditya.jain/.conda/envs/milamoth/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mila/a/aditya.jain/.conda/envs/milamoth/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mila/a/aditya.jain/mothAI/classification_moths/data/mothdataset.py", line 38, in __getitem__
    image      = Image.open(image_path)
  File "/home/mila/a/aditya.jain/.conda/envs/milamoth/lib/python3.7/site-packages/PIL/Image.py", line 3124, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/Tmp/slurm.1934960.0/home/mila/a/aditya.jain/scratch/GBIF_Data/moths_uk/Erebidae/Idia/Idia lubricalis/1846834655.jpg'
  0% 0/1 [04:25<?, ?it/s]