
cpu


Downloading model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 57.9M/57.9M [00:04<00:00, 12.5MB/s]
Traceback (most recent call last):
  File "/Users/lbokeria/Documents/projects/gbif-species-trainer-AMI-fork/model_training/04-train_model.py", line 356, in <module>
    train_model(args)
  File "/Users/lbokeria/Documents/projects/gbif-species-trainer-AMI-fork/model_training/04-train_model.py", line 167, in train_model
    for image_batch, label_batch in train_dataloader:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data.append(next(self.dataset_iter))
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/pipeline.py", line 64, in iterator
    for sample in self.iterator1():
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/filters.py", line 415, in _map_tuple
    for sample in data:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/filters.py", line 392, in _to_tuple
    for sample in data:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/filters.py", line 297, in _map
    for sample in data:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/filters.py", line 208, in _shuffle
    for sample in data:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/tariterators.py", line 218, in group_by_keys
    for filesample in data:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/tariterators.py", line 171, in tar_file_expander
    for source in data:
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/tariterators.py", line 96, in url_opener
    if handler(exn):
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/filters.py", line 80, in reraise_exception
    raise exn
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/tariterators.py", line 91, in url_opener
    stream = gopen.gopen(url, **kw)
  File "/Users/lbokeria/miniforge3/envs/gbif-species-trainer-AMI-fork/lib/python3.9/site-packages/webdataset/gopen.py", line 380, in gopen
    return open(url, mode, buffering=bufsize)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lbokeria/Documents/projects/gbif-species-trainer-AMI-fork/model_training/train/train-500-000342.tar'